# Generated by Django 6.0.1 on 2026-01-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registromanutencao_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registromanutencao',
            old_name='foto',
            new_name='foto_1',
        ),
        migrations.AddField(
            model_name='registromanutencao',
            name='foto_2',
            field=models.ImageField(blank=True, null=True, upload_to='manutencoes/'),
        ),
        migrations.AddField(
            model_name='registromanutencao',
            name='foto_3',
            field=models.ImageField(blank=True, null=True, upload_to='manutencoes/'),
        ),
    ]
